version: 2.1

jobs:
  build:
    working_directory: ~/spotify-heroic-datasource
    docker:
      - image: circleci/node:4.8.2
    steps:
     - checkout
     - node/install-packages:
         pkg-manager: yarn
     - run:
         name: "Build with yarn"
         command: |
           yarn lint
           yarn build
           yarn test
     - run:
         name: "Before deploy"
         command: |
           git config --local user.name "CircleCI"
           git config --local user.email "no-reply@circle-ci.com"
           zip spotify-heroic-datasource -r dist/
           git tag "build-${TRAVIS_BUILD_NUMBER}"
  
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
