on:
  push:
    branches:
      - "master"

name: Github Release
jobs:
  deploy:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "spotify-heroic-datasource.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
