name: Node.js Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  on_merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare on merge"
        if: github.event.pull_request.merged == 'true'
        uses: actions/checkout@v2
      - name: "Setup node on merge"
        if: github.event.pull_request.merged == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: "Publish on merge"
        if: github.event.pull_request.merged == 'true'
        run: | 
          yarn
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
