on:
  push:
    branches:
      - "master"

name: Github Release
jobs:
  deploy:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        run: npm install
      - name: yarn lint
        run: yarn lint
      - name: yarn build
        run: yarn build
      - name: yarn test
        run: yarn test
      - name: Create Zip
        run: zip spotify-heroic-datasource -r dist/
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "spotify-heroic-datasource.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
